---
abstract: 'A POE Filter for creating FINGER servers.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::Deep: 0.103
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-Finger
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  POE: 0.38
  POE::Filter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
